"""Add borrowed column to book table

Revision ID: 89cb5f189487
Revises: 
Create Date: 2023-05-06 23:40:24.098130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "89cb5f189487"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Drop the temporary table if it exists
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_book;")

    # Create the new table
    op.create_table(
        "_alembic_tmp_book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("author", sa.String(length=50), nullable=False),
        sa.Column("publisher", sa.String(length=50), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("pages", sa.Integer(), nullable=False),
        sa.Column("borrowed", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id", sa.INTEGER(), nullable=True))
        batch_op.drop_column("borrowed")

    # ### end Alembic commands ###
